name: "KiCad actions"
description: "A GitHub action that can generate and check KiCad schematics and PCBs."
branding:
  icon: "cpu"
  color: "green"

inputs:
  # Input file location
  input_file:
    description: "The YAML input file containing the generate information."
