name: "KiCad actions"
description: "Install and setup kicad."
branding:
  icon: "cpu"
  color: "green"

inputs:
  # Schematic input file
  schematic_file:
    description: "Location of the .kicad_sch file"

  # ERC run
  run_erc:
    description: "Run the ERC on the schematic"
    default: false

  erc_output_file_name:
    description: "Output file name of ERC report"
    default: "erc.rpt"

  # Schematic PDF output
  schematic_output_pdf:
    description: "Run the PDF export of the schematic"
    default: false

  schematic_output_pdf_file_name:
    description: "Output file name of PDF schematic"
    default: "schematic.pdf"

  schematic_output_black_white:
    description: "Run the PDF, SVG and DXF export in black and white"
    default: false

  # Schematic SVG output
  schematic_output_svg:
    description: "Run the SVG export of the schematic"
    default: false

  schematic_output_svg_folder_name:
    description: "Output folder name of SVG schematic"
    default: "schematics"

  # Schematic DXF output
  schematic_output_dxf:
    description: "Run the DXF export of the schematic"
    default: false

  schematic_output_dxf_folder_name:
    description: "Output folder name of DXF schematic"
    default: "schematics"

  # Schematic HPGL output
  schematic_output_hpgl:
    description: "Run the HPGL export of the schematic"
    default: false

  schematic_output_hpgl_folder_name:
    description: "Output folder name of HPGL schematic"
    default: "schematics"

  # Schematic PS output
  schematic_output_ps:
    description: "Run the PS export of the schematic"
    default: false

  schematic_output_ps_folder_name:
    description: "Output folder name of PS schematic"
    default: "schematics"

  # Schematic BOM output
  schematic_output_bom:
    description: "Run the BOM export of the schematic"
    default: false

  schematic_output_bom_file_name:
    description: "Output file name of the BOM"
    default: "bom.csv"

  # Schematic netlist output
  schematic_output_netlist:
    description: "Run the netlist export of the schematic"
    default: false

  schematic_output_netlist_file_name:
    description: "Output file name of the netlist"
    default: "netlist.net"

  # PCB input file
  pcb_file:
    description: "Location of the .kicad_pcb file"

  # DRC run
  run_drc:
    description: "Run the DRC on the PCB"
    default: false

  drc_output_file_name:
    description: "Output file name of DRC report"
    default: "drc.rpt"

  # pcb_gerbers:
  #   description: "Whether to generate Gerbers from PCB"
  #   default: false
  # pcb_gerbers_file:
  #   description: "Output file name of Gerbers ZIP"
  #   default: "gbr.zip"
  # pcb_image:
  #   description: "Whether to render the PCB image"
  #   default: false
  # pcb_image_path:
  #   description: "Where to put the top.png and bottom.png"
  #   default: "images"
  # pcb_model:
  #   description: "Whether to export the PCB model"
  #   default: false
  # pcb_model_file:
  #   description: "Output file name of PCB model"
  #   default: "pcb.step"
  # pcb_model_flags:
  #   description: "Flags to add when exporting STEP files"
  #   default: "--no-unspecified --no-dnp --include-tracks  --include-pads  --include-zones"

runs:
  using: "docker"
  image: "Dockerfile"
