name: "KiCad actions"
description: "A GitHub action that can generate and check KiCad schematics and PCBs."
branding:
  icon: "cpu"
  color: "green"

inputs:
  # YAML input file
  input_file:
    description: "Path to the YAML input file"

runs:
  using: "docker"
  image: "Dockerfile"
