name: Auto Update and Release KiCad Versions

on:
  workflow_dispatch: # Allows manual trigger
    inputs:
      action_version:
        description: "Action version (e.g., v1)"
        required: true
        default: "v1"
      kicad_versions:
        description: "Comma-separated KiCad versions (e.g., 8.0,9.0)"
        required: true
        default: "8.0,9.0"

jobs:
  update-dockerfile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kicad_version: ${{ fromJson(inputs.kicad_versions) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create a new branch for KiCad ${{ matrix.kicad_version }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          BRANCH_NAME="release-k${{ matrix.kicad_version }}"
          git checkout -b $BRANCH_NAME

      - name: Update Dockerfile with KiCad Version ${{ matrix.kicad_version }}
        run: |
          sed -i 's|FROM kicad/kicad:.*|FROM kicad/kicad:${{ matrix.kicad_version }}|' Dockerfile
          git add Dockerfile
          git commit -m "Update Dockerfile for KiCad ${{ matrix.kicad_version }}"
          git push origin HEAD

      - name: Create Git Tag and Release
        run: |
          TAG="${{ inputs.action_version }}-k${{ matrix.kicad_version }}"
          git tag $TAG
          git push origin $TAG
          gh release create $TAG --title "Release $TAG" --notes "Updated KiCad to version ${{ matrix.kicad_version }}"
