name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - "*.md"
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  test-no-arguments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run KiCad actions
        uses: ./

  test-no-schematic-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run KiCad actions
        id: kicad_actions
        uses: ./
        with:
          schematic_output_pdf: true
        continue-on-error: true

      - name: Verify file check result
        run: |
          if [[ "${{ steps.kicad_actions.outcome }}" != "failure" ]]; then
            echo "::error::Expected failure, but step succeeded!"
            exit 1
          fi
        shell: bash

  test-no-pcb-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run KiCad actions
        id: kicad_actions
        uses: ./
        with:
          pcb_output_drill: true
        continue-on-error: true

      - name: Verify file check result
        run: |
          if [[ "${{ steps.kicad_actions.outcome }}" != "failure" ]]; then
            echo "::error::Expected failure, but step succeeded!"
            exit 1
          fi
        shell: bash

  test-erc-drc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_name: ["erc-failure", "erc-success", "drc-failure", "drc-success"]
        include:
          - test_name: erc-failure
            erc: true
            drc: false
            schematic_file_name: tests/kicad-project-failure/kicad-project.kicad_sch
            pcb_file_name: null
            result: failure
          - test_name: erc-success
            erc: true
            drc: false
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            pcb_file_name: null
            result: success
          - test_name: drc-failure
            erc: false
            drc: true
            schematic_file_name: null
            pcb_file_name: tests/kicad-project-failure/kicad-project.kicad_pcb
            result: failure
          - test_name: drc-success
            erc: false
            drc: true
            schematic_file_name: null
            pcb_file_name: tests/kicad-project-success/kicad-project.kicad_pcb
            result: success
    steps:
      - uses: actions/checkout@v4
      - name: Run ERC/DRC check
        id: check
        uses: ./
        with:
          run_erc: ${{ matrix.erc }}
          run_drc: ${{ matrix.drc }}
          schematic_file_name: ${{ matrix.schematic_file_name }}
          pcb_file_name: ${{ matrix.pcb_file_name }}
        continue-on-error: true
      - name: Verify ERC/DRC step result
        run: |
          if [[ "${{ matrix.result }}" == "failure" && "${{ steps.check.outcome }}" != "failure" ]]; then
            echo "::error::Expected failure, but step succeeded!"
            exit 1
          fi
          if [[ "${{ matrix.result }}" == "success" && "${{ steps.check.outcome }}" == "failure" ]]; then
            echo "::error::Expected success, but step failed!"
            exit 1
          fi
        shell: bash

  test-schematic-outputs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_name:
          [
            "pdf",
            "pdf-black-white",
            "svg",
            "svg-black-white",
            "dxf",
            "dxf-black-white",
            "hpgl",
            "ps",
            "ps-black-white",
            "bom",
            "netlist",
          ]
        include:
          - test_name: pdf
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_pdf
            expected_file: schematic.pdf
            schematic_output_black_white: false
          - test_name: pdf-black-white
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_pdf
            expected_file: schematic.pdf
            schematic_output_black_white: true
          - test_name: svg
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_svg
            expected_file: schematics/kicad-project.svg
            schematic_output_black_white: false
          - test_name: svg-black-white
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_svg
            expected_file: schematics/kicad-project.svg
            schematic_output_black_white: true
          - test_name: dxf
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_dxf
            expected_file: schematics/kicad-project.dxf
            schematic_output_black_white: false
          - test_name: dxf-black-white
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_dxf
            expected_file: schematics/kicad-project.dxf
            schematic_output_black_white: true
          - test_name: hpgl
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_hpgl
            expected_file: schematics/kicad-project.plt
            schematic_output_black_white: false
          - test_name: ps
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_ps
            expected_file: schematics/kicad-project.ps
            schematic_output_black_white: false
          - test_name: ps-black-white
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_ps
            expected_file: schematics/kicad-project.ps
            schematic_output_black_white: true
          - test_name: bom
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_bom
            expected_file: bom.csv
          - test_name: netlist
            schematic_file_name: tests/kicad-project-success/kicad-project.kicad_sch
            output_flag: schematic_output_netlist
            expected_file: netlist.net
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run schematic output generation
        id: generate_output
        uses: ./
        with:
          schematic_file_name: ${{ matrix.schematic_file_name }}
          ${{ matrix.output_flag }}: true
          schematic_output_black_white: ${{ matrix.schematic_output_black_white || false }}

      - name: Verify output file
        run: |
          if [[ ! -f "${{ matrix.expected_file }}" ]]; then
            echo "::error::Expected output file '${{ matrix.expected_file }}' not found!"
            exit 1
          fi
        shell: bash

  test-pcb-outputs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_name:
          [
            "drill-excellon",
            "drill-gerber",
            "gerbers-seperate",
            "gerbers-zip",
            "dxf",
          ]
        include:
          - test_name: drill-excellon
            pcb_file_name: tests/kicad-project-success/kicad-project.kicad_pcb
            output_flag: pcb_output_drill
            expected_files: drill/kicad-project.drl
          - test_name: drill-gerber
            pcb_file_name: tests/kicad-project-success/kicad-project.kicad_pcb
            output_flag: pcb_output_drill
            expected_files: |
              "drill/kicad-project-PTH-drl.gbr"
              "drill/kicad-project-NPTH-drl.gbr"
            pcb_output_drill_format: gerber
          - test_name: gerbers-seperate
            pcb_file_name: tests/kicad-project-success/kicad-project.kicad_pcb
            output_flag: pcb_output_gerbers
            pcb_output_layers: "F.Cu,F.Mask,F.SilkS"
            expected_files: |
              "gerbers/kicad-project-F_Cu.gbr"
              "gerbers/kicad-project-F_Mask.gbr"
              "gerbers/kicad-project-F_SilkS.gbr"
          - test_name: gerbers-zip
            pcb_file_name: tests/kicad-project-success/kicad-project.kicad_pcb
            output_flag: pcb_output_gerbers
            expected_files: "gerbers.zip"
            pcb_output_gerbers_zip: true
          - test_name: dxf
            pcb_file_name: tests/kicad-project-success/kicad-project.kicad_pcb
            output_flag: pcb_output_dxf
            pcb_output_layers: "F.Cu,F.Mask,F.SilkS"
            expected_files: "pcb.dxf"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run schematic output generation
        id: generate_output
        uses: ./
        with:
          pcb_file_name: ${{ matrix.pcb_file_name }}
          ${{ matrix.output_flag }}: true
          pcb_output_drill_format: ${{ matrix.pcb_output_drill_format || 'excellon' }}
          pcb_output_gerbers_zip: ${{ matrix.pcb_output_gerbers_zip || false }}
          pcb_output_layers: ${{ matrix.pcb_output_layers || null }}

      - name: Verify output files
        run: |
          echo "${{ matrix.expected_files }}" | while IFS= read -r file; do
            if [[ -n "$file" && ! -f "$file" ]]; then
              echo "::error::Expected output file '$file' not found!"
              exit 1
            fi
          done
        shell: bash
    # TODO CHECK ERC DRC OUTPUT FILE
