name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - "*.md"
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  test-no-arguments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run KiCad actions
        uses: ./

  test-no-schematic-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run KiCad actions
        id: kicad_actions
        uses: ./
        with:
          schematic_output_pdf: true
        continue-on-error: true

      - name: Verify Check File Step Result
        run: |
          if [[ "${{ steps.kicad_actions.outcome }}" != "failure" ]]; then
            echo "Expected failure, but step succeeded!"
            exit 1
          fi
        shell: bash

  test-erc-drc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-name: ["erc-failure", "erc-success"]
        include:
          - test-name: erc-failure
            erc: true
            drc: false
            schematic_file: tests/kicad-project-failure/kicad-project.kicad_sch
            pcb_file: null
            result: failure
          - test-name: erc-success
            erc: true
            drc: false
            schematic_file: tests/kicad-project-success/kicad-project.kicad_sch
            pcb_file: null
            result: success
          - test-name: drc-failure
            erc: false
            drc: true
            schematic_file: null
            pcb_file: tests/kicad-project-failure/kicad-project.kicad_pcb
            result: failure
          - test-name: drc-success
            erc: false
            drc: true
            schematic_file: null
            pcb_file: tests/kicad-project-success/kicad-project.kicad_pcb
            result: success
    steps:
      - uses: actions/checkout@v4
      - name: Run ERC/DRC check
        id: check
        uses: ./
        with:
          run_erc: ${{ matrix.erc }}
          run_drc: ${{ matrix.drc }}
          schematic_file: ${{ matrix.schematic_file }}
          pcb_file: ${{ matrix.pcb_file }}
        continue-on-error: true
      - name: Verify ERC/DRC step result
        run: |
          if [[ "${{ matrix.result }}" == "failure" && "${{ steps.check.outcome }}" != "failure" ]]; then
            echo "Expected failure, but step succeeded!"
            exit 1
          fi
          if [[ "${{ matrix.result }}" == "success" && "${{ steps.check.outcome }}" == "failure" ]]; then
            echo "Expected success, but step failed!"
            exit 1
          fi
        shell: bash
