name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - "*.md"
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  test-kicad-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run KiCad Action
        uses: ./
        with:
          kicad_version: "8.0"

      - name: Verify KiCad Installation
        run: kicad-cli --version
